### ISSUE TITLE
This is an awesome list!

### ISSUE THREAD

**Issue by stichbury** [fkromer/awesome-kedro#1]
Hi @fkromer 

Thanks Florian for putting this list together, it's really nice to have all these links together. If it's OK with you, I'm going to point to it from the [kedro-community](https://github.com/quantumblacklabs/kedro-community) repo.

Jo

**Comment by fkromer** [comment]
@stichbury Thanks a lot! I already announced the list here https://discourse.kedro.community/t/kedro-is-awesome/237. However feel free to spread the word where ever you can.

**Comment by stichbury** [comment]
Done! Thanks so much 🚀
